import React from "react";
import GenerateTable from "@/components/ui/GenerateTable";
import Navbar from "@/components/Navbar";

const incidenthistory = [
  {
    id: "Inc 044",
    summary:
      "Hallucinations were observed in customer support bots during live user interactions",
    status: "Resolved",
    date: "Oct 31, 2025",
  },
  {
    id: "Inc 043",
    summary: "Unexpected model refusals occurred for benign user prompts",
    status: "Resolved",
    date: "Sep 8, 2025",
  },
  {
    id: "Inc 042",
    summary:
      "Elevated response times were observed in the inference engine under production load",
    status: "Resolved",
    date: "Aug 23, 2025",
  },
  {
    id: "Inc 041",
    summary:
      "API rate limiting failed to enforce thresholds during sustained traffic",
    status: "Resolved",
    date: "Aug 18, 2025",
  },
  {
    id: "Inc 040",
    summary:
      "Training data ingestion experienced repeated timeouts during batch processing",
    status: "Resolved",
    date: "Oct 31, 2025",
  },
];

const HistoryPage = () => {
  const hasIncidents = incidenthistory.length > 0;

  return (
    <main>
      <Navbar showBreadcrumb={false}/>
      <section className="min-h-screen max-w-266 mx-auto flex flex-col gap-10 mt-23.5">
        <div className="text-center">
          <h1 className="text-[36px] font-bold">Incident History</h1>
          <p>A record of generated postmortems of past incidents</p>
        </div>
        {hasIncidents ? (
          <GenerateTable incidents={incidenthistory} />
        ) : (
          <div className="flex flex-col items-center justify-center mt-[300px] text-center">
            <p className="text-lg font-medium mb-2">
              No incidents have been recorded yet.
            </p>
            <p className="text-sm text-gray-400">
              When incidents occur, generated postmortems will appear here
            </p>
          </div>
        )}
      </section>
      <footer className="text-center text-[14px]">
        Automatically generated by Postmortor · Internal use only · Confidential
      </footer>
    </main>
  );
};

export default HistoryPage;
